SET IDENTITY_INSERT [dbo].[Mantenimientos] ON
INSERT INTO [dbo].[Mantenimientos] ([Id], [FechaMantenimiento], [Descripcion], [Costo], [Operador], [CabanaNumeroHabitacion]) VALUES (1, N'2023-04-29 12:22:00', N'Prueba', 5, N'Felipe', 3)
INSERT INTO [dbo].[Mantenimientos] ([Id], [FechaMantenimiento], [Descripcion], [Costo], [Operador], [CabanaNumeroHabitacion]) VALUES (2, N'2023-04-29 12:28:00', N'tema1', 1211, N'Felipe', 3)
INSERT INTO [dbo].[Mantenimientos] ([Id], [FechaMantenimiento], [Descripcion], [Costo], [Operador], [CabanaNumeroHabitacion]) VALUES (3, N'2023-04-12 12:47:00', N'Prueba', 6, N'Felipe', 5)
INSERT INTO [dbo].[Mantenimientos] ([Id], [FechaMantenimiento], [Descripcion], [Costo], [Operador], [CabanaNumeroHabitacion]) VALUES (4, N'2023-04-29 13:06:00', N'a', 1234, N'Felipe', 3)
INSERT INTO [dbo].[Mantenimientos] ([Id], [FechaMantenimiento], [Descripcion], [Costo], [Operador], [CabanaNumeroHabitacion]) VALUES (6, N'2023-04-30 13:24:00', N'Prueba', 4, N'Felipe', 3)
INSERT INTO [dbo].[Mantenimientos] ([Id], [FechaMantenimiento], [Descripcion], [Costo], [Operador], [CabanaNumeroHabitacion]) VALUES (7, N'2023-04-30 13:28:00', N'Prueba', 49, N'Felipe', 3)
INSERT INTO [dbo].[Mantenimientos] ([Id], [FechaMantenimiento], [Descripcion], [Costo], [Operador], [CabanaNumeroHabitacion]) VALUES (8, N'2023-04-30 13:30:00', N'qwerty', 18, N'Felipe', 3)
INSERT INTO [dbo].[Mantenimientos] ([Id], [FechaMantenimiento], [Descripcion], [Costo], [Operador], [CabanaNumeroHabitacion]) VALUES (9, N'2023-05-01 13:30:00', N'qwerty', 18, N'Felipe', 3)
INSERT INTO [dbo].[Mantenimientos] ([Id], [FechaMantenimiento], [Descripcion], [Costo], [Operador], [CabanaNumeroHabitacion]) VALUES (10, N'2023-05-01 13:35:00', N'qwerty', 6, N'Felipe', 3)
INSERT INTO [dbo].[Mantenimientos] ([Id], [FechaMantenimiento], [Descripcion], [Costo], [Operador], [CabanaNumeroHabitacion]) VALUES (11, N'2023-05-01 13:38:00', N'qwerty', 5, N'Felipe', 3)
INSERT INTO [dbo].[Mantenimientos] ([Id], [FechaMantenimiento], [Descripcion], [Costo], [Operador], [CabanaNumeroHabitacion]) VALUES (12, N'2023-05-02 13:42:00', N'Prueba', 5, N'Felipe', 3)
INSERT INTO [dbo].[Mantenimientos] ([Id], [FechaMantenimiento], [Descripcion], [Costo], [Operador], [CabanaNumeroHabitacion]) VALUES (13, N'2023-04-30 13:46:00', N'Prueba', 6, N'Felipe', 1)
INSERT INTO [dbo].[Mantenimientos] ([Id], [FechaMantenimiento], [Descripcion], [Costo], [Operador], [CabanaNumeroHabitacion]) VALUES (14, N'2023-05-02 13:49:00', N'qwerty', 12, N'Felipe', 4)
INSERT INTO [dbo].[Mantenimientos] ([Id], [FechaMantenimiento], [Descripcion], [Costo], [Operador], [CabanaNumeroHabitacion]) VALUES (15, N'2023-05-01 20:44:00', N'Prueba1', 12, N'Felipe', 5)
INSERT INTO [dbo].[Mantenimientos] ([Id], [FechaMantenimiento], [Descripcion], [Costo], [Operador], [CabanaNumeroHabitacion]) VALUES (16, N'2023-05-01 20:44:00', N'Prueba1', 12, N'Felipe', 5)
INSERT INTO [dbo].[Mantenimientos] ([Id], [FechaMantenimiento], [Descripcion], [Costo], [Operador], [CabanaNumeroHabitacion]) VALUES (17, N'2023-05-01 20:45:00', N'Prueba2', 12, N'Felipe', 5)
INSERT INTO [dbo].[Mantenimientos] ([Id], [FechaMantenimiento], [Descripcion], [Costo], [Operador], [CabanaNumeroHabitacion]) VALUES (18, N'2023-04-30 19:41:00', N'Prueba mantenimiento 8/5', 122, N'Lunes', 1)
INSERT INTO [dbo].[Mantenimientos] ([Id], [FechaMantenimiento], [Descripcion], [Costo], [Operador], [CabanaNumeroHabitacion]) VALUES (19, N'2023-04-30 19:00:00', N'Prueba mantenimiento 8/5', 123, N'lunes', 1)
INSERT INTO [dbo].[Mantenimientos] ([Id], [FechaMantenimiento], [Descripcion], [Costo], [Operador], [CabanaNumeroHabitacion]) VALUES (20, N'2023-05-08 19:00:00', N'Prueba mantenimiento 8/5', 124, N'lunes', 1)
INSERT INTO [dbo].[Mantenimientos] ([Id], [FechaMantenimiento], [Descripcion], [Costo], [Operador], [CabanaNumeroHabitacion]) VALUES (21, N'2023-05-10 14:33:00', N'Ultima prueba de mantenimiento', 500, N'Felipe', 1)
SET IDENTITY_INSERT [dbo].[Mantenimientos] OFF
