INSERT INTO [dbo].[Tipos] ([Nombre], [Descripcion], [CostoHuesped]) VALUES (N'Doble', N'una habitación asignada a dos personas. Puede tener una o más camas.', 130)
INSERT INTO [dbo].[Tipos] ([Nombre], [Descripcion], [CostoHuesped]) VALUES (N'Doble-doble', N'una habitación con dos camas dobles (o tal vez queen). Puede ser ocupado por una o más personas.', 310)
INSERT INTO [dbo].[Tipos] ([Nombre], [Descripcion], [CostoHuesped]) VALUES (N'Estudio', N'una habitación con una cama de estudio, un sofá que se puede convertir en una cama. También puede tener una cama adicional.', 340)
INSERT INTO [dbo].[Tipos] ([Nombre], [Descripcion], [CostoHuesped]) VALUES (N'Individual', N'una habitación asignada a una persona. Puede tener una o más camas.', 100)
INSERT INTO [dbo].[Tipos] ([Nombre], [Descripcion], [CostoHuesped]) VALUES (N'Junior Suite', N'Una habitación individual con una cama y una sala de estar. A veces, el área para dormir está en un dormitorio separado del salón o la sala de estar.', 400)
INSERT INTO [dbo].[Tipos] ([Nombre], [Descripcion], [CostoHuesped]) VALUES (N'King', N'una habitación con una cama king-size. Puede ser ocupado por una o más personas.', 250)
INSERT INTO [dbo].[Tipos] ([Nombre], [Descripcion], [CostoHuesped]) VALUES (N'Master Suite', N'Un salón o sala de estar conectada a uno o más dormitorios.', 370)
INSERT INTO [dbo].[Tipos] ([Nombre], [Descripcion], [CostoHuesped]) VALUES (N'Quad', N'una sala asignada a cuatro personas. Puede tener dos o más camas', 190)
INSERT INTO [dbo].[Tipos] ([Nombre], [Descripcion], [CostoHuesped]) VALUES (N'Queen', N'una habitación con una cama de matrimonio. Puede ser ocupado por una o más personas', 220)
INSERT INTO [dbo].[Tipos] ([Nombre], [Descripcion], [CostoHuesped]) VALUES (N'Triple', N'una habitación asignada a tres personas. Puede tener dos o más camas', 160)
INSERT INTO [dbo].[Tipos] ([Nombre], [Descripcion], [CostoHuesped]) VALUES (N'Twin', N'una habitación con dos camas. Puede ser ocupado por una o más personas.', 280)
